### ISSUE TITLE
[ left open for anyone else wanting the pop.lmp ] No .pak file, add installation instructions for the unbuilt repo 

### ISSUE THREAD

**Issue by DeerTears** [MissLavender-LQ/LibreQuake#12]
Since I haven't been able to find the .pak file in this repo, and the only installation instructions are on installing this mod as a .pak (and building it requires other tools) I figure it's good to include direct instructions for newbies (like myself) in the README for installing the mod as it comes here if you already have a copy of Quake 1. 

Lemme know if I wrote down anything incorrect or just in a confusing manner. This is how I did it on Windows 10 with Quakespasm that holds the regular pak0.pak and pak1.pak. I don't think this works for Shareware version since it forbids custom map loading.

How To Play
Quake 1 Owners:
1. Clone/Download repository
2. Copy the /lq1 subfolder
3. Paste it in the root of your current Quake installation, right next to /id1
In-Game:
Type "game lq1" into console. If the background and font changes, it's installed correctly.

This instruction was suggested to me by MissLav

Command-Line (Linux):
In the game's install folder, type "./.EngineNameHere -game lq1"

**Comment by MissLav** [comment]
you currently launch it the same way you would launch a quake mod like Arcane Dimensions the repo is already build ina sense since u can launch it from winquake and dosquake
u can rename lq1 to id1 or launch the engine and type game id1 in con

**Comment by MissLav** [comment]
oh wait
i didnt read the full thing

**Comment by 20kdc** [comment]
Something to note:
```
$ ../wq -game lq1
FindFile: can't find gfx/pop.lmp
Playing shareware version.
Error: You must have the registered version to use modified games
```
(I'm fully aware that in a source port such as DarkPlaces, this does not occur. Still.)
It appears that the (GPL'd in hex form) pop.lmp was removed for some reason...?

**Comment by mmillar-bolis** [comment]
Lacking a proof-of-purchase lump (pop.lmp) *will* still affect more conservative source ports such as Quakespasm, QSS, and vkQuake.

`pop.png` was present in the source tree until it was removed in commit [3bba32a](https://github.com/MissLav/LibreQuake/commit/3bba32a68a4529fc71f20bd8af234d2eaa2e0322) on 2019-11-26. `pop.lmp` was removed in commits [1f5c850](https://github.com/MissLav/LibreQuake/commit/1f5c850be5adc981d327496022c6070d0ee256a6) and [c961422](https://github.com/MissLav/LibreQuake/commit/c9614226111a34c7704ecf9dd3b81ec7cf54b187) on 2021-04-27. 

Although a clear reason is not really given beyond the statement of getting rid of it, I believe the binary form of `pop.lmp` is subject to Quake's commercial license, so it seems likely that is why it was removed. Another reason may be, based on the above directions, that LibreQuake is no longer intended to be run on an engine without a present and fully licensed copy of the `id1` resource data due to the inability to reliably work around the lack of a `pop.lmp` file. These are just my guesses.

@20kdc do you have any more information on the GPL licensing of any form of `pop.lmp`? I'm not able to find anything referring to it, so your info or source may help.

**Comment by MissLav** [comment]
> Lacking a proof-of-purchase lump (pop.lmp) _will_ still affect more conservative source ports such as Quakespasm, QSS, and vkQuake.
> 
> `pop.png` was present in the source tree until it was removed in commit [3bba32a](https://github.com/MissLav/LibreQuake/commit/3bba32a68a4529fc71f20bd8af234d2eaa2e0322) on 2019-11-26. `pop.lmp` was removed in commits [1f5c850](https://github.com/MissLav/LibreQuake/commit/1f5c850be5adc981d327496022c6070d0ee256a6) and [c961422](https://github.com/MissLav/LibreQuake/commit/c9614226111a34c7704ecf9dd3b81ec7cf54b187) on 2021-04-27.
> 
> Although a clear reason is not really given beyond the statement of getting rid of it, I believe the binary form of `pop.lmp` is subject to Quake's commercial license, so it seems likely that is why it was removed. Another reason may be, based on the above directions, that LibreQuake is no longer intended to be run on an engine without a present and fully licensed copy of the `id1` resource data due to the inability to reliably work around the lack of a `pop.lmp` file. These are just my guesses.
> 
> @20kdc do you have any more information on the GPL licensing of any form of `pop.lmp`? I'm not able to find anything referring to it, so your info or source may help.

it was removed because the version we were using was based on the GPL version and we thought it would be better if librequake's github only contained bsd3 to avoid confusion even tho we could likely point out the gpl licensed stuff and it would be fine

**Comment by MissLav** [comment]
also heres the gpl version of the pop.lmp its located in the engine code 
![image](https://user-images.githubusercontent.com/51702517/132604530-82f911ab-8ac9-4e01-bdb8-7a422425f059.png)
and here it is on the idsoftware github
https://github.com/id-Software/Quake/blob/bf4ac424ce754894ac8f1dae6a3981954bc9852d/QW/client/common.c

**Comment by MissLav** [comment]
[pop.lmp.zip](https://github.com/MissLav/LibreQuake/files/7132560/pop.lmp.zip)
heres the gpl version of the pop.lmp if u wanna run it for now just fyi (you sortta gotta run the game with quake atm cuz we dont have temp files for all the models

**Comment by mmillar-bolis** [comment]
This is awesome info, thank you! Splitting out the GPL stuff makes perfect sense.

I suppose one thing you could do towards the end of the project is produce `.pak` files based on their license. So for example, all of the BSD3 code might go in `pak0.pak` while any GPL code such as `pop.lmp` would go in `pak1.pak`. Just a thought.

Anyway, sorry if these comments were unnecessary. Your info was greatly appreciated!

**Comment by MissLav** [comment]
> This is awesome info, thank you! Splitting out the GPL stuff makes perfect sense.
> 
> I suppose one thing you could do towards the end of the project is produce `.pak` files based on their license. So for example, all of the BSD3 code might go in `pak0.pak` while any GPL code such as `pop.lmp` would go in `pak1.pak`. Just a thought.
> 
> Anyway, sorry if these comments were unnecessary. Your info was greatly appreciated!

that could 100% be done thats a great idea ill put the progs dat at and the pop.lmp in pak0 and have everything else in pak1 or vise versa or i could make a pop2 since it just loads what ever paks are in that dir

its a bit easier to talk via the discord server / matrix community if u wanna join those

**Comment by Calinou** [comment]
I remember a statement from Carmack saying the Quake color palette is under the public domain (more permissive than GPL), but I doubt this applies to `pop.lmp`.

**Comment by MotoLegacy** [comment]
Can this be closed now that `pop.lmp` is distributed? @MissLavender-LQ

**Comment by MissLavender-LQ** [comment]
yep 1 sec
